### ISSUE TITLE
re: https://developer.blender.org/T37230

### ISSUE THREAD

**Issue by meta-androcto** [Antonioya/blender#11]
hi, I've recently made some changes to your https://developer.blender.org/T37230 page.
Sorry it's taken so long, i was inactive for some time.
If your still interested I can have Archimesh reviewed for inclusion in contrib addons first, then furthur review for release addons.
Thanks.
Great scripts.

**Comment by Antonioya** [comment]
Well, I would like to include Archimesh and MeasureIt in Blender, but I don't know what implies to do it (obligations and so on) and how submit them.

Could you give more information?
