### ISSUE TITLE
Report: Error

### ISSUE THREAD

**Issue by ElektroFox** [Antonioya/blender#13]
Traceback (most recent call last):
      File "C:\Program Files\Blender\2.74\scripts\addon_utils.py", line 325, in enable mod.register()

       File "C:\Program Files\Blender\2.74\scripts\addons\archimesh\_init_.py", line 153, in register bpy.utils.register_class(room_maker.RoomGeneratorPanel)

ValueError: register_class(...): already registered as a subclass

I get that every time I try to enable, regardless of version. Did I do something wrong?

**Comment by cesar126a** [comment]
**System Information**
  OS X Yosemite version 10.10.3 and NVIDIA GeForce GT 750M 2048 MB

  **Blender Version**
  Broken: 2.75 c6042b

  **Short description of error**
  Any inserted object that uses Properties panel (N) to define parameters will crash Blender. Objects can be edited only after deselecting and cancelling link with parameters.

  **Exact steps for others to reproduce the error**
  Example: Create rectangle and insert door, on property panel (N) change hight ... Blender will crash

**Comment by Antonioya** [comment]
cwsar126a, I have tested in Windows version and works. I cannot test the program in OSX, so cannot help you.

**Comment by temkin** [comment]
@cesar126a @Antonioya  OS X Yosemite 10.10.3  Blender 2.75 same bug

**Comment by ElektroFox** [comment]
Glad my question got hijacked that was super useful.
