### ISSUE TITLE
Doc Scenes addon error

### ISSUE THREAD

**Issue by johantri** [Antonioya/blender#14]
Hi Antonioya,

Thank you for this wonderful addon. I'm using this as my storyboard helper tool to export as html and i can print it for hardcopy document. However i found a little problem when using Blender 2.76 and grease pencil drawing. Or is it me not using this addon correctly? Thank you for your time :)

![doc scene error](https://cloud.githubusercontent.com/assets/13281082/10747496/6acb589e-7c88-11e5-9df7-943b1018321f.png)

**Comment by Antonioya** [comment]
johantri, could you provide me a .blend file with the error (or only a small part) ?

Send to blendergit@gmail.com

**Comment by johantri** [comment]
here you go.

https://drive.google.com/open?id=0BypbXbJ3amiMbEhCY2gxbExLQTQ

**Comment by Antonioya** [comment]
@johantri Could you try new version v1.1?

**Comment by johantri** [comment]
It's working great! I'm very happy with the result. Thank you very much. I'm also curious to know how to add written notes in it. I chose the keyframe and notes option one.
![stb_test](https://cloud.githubusercontent.com/assets/13281082/10783961/e8f2a712-7d8d-11e5-9bcb-668b362d020e.jpg)

**Comment by Antonioya** [comment]
@johantri I'm working in notes. Now you must write manually using an external editor or using a pencil over the paper.
