### ISSUE TITLE
No simple measurements

### ISSUE THREAD

**Issue by elersong** [Antonioya/blender#19]
Using blender 2.75a, I'm able to measure direct distances between 2 vertices on 2 objects. However, I'm unable to measure the vertical distance (z axis only) between the topmost point of one object and the lowest point of another object. Likewise, I cannot measure the horizontal distance (x or y axis only) between two objects.

**Comment by Antonioya** [comment]
Review all the youtube videos.You will see you can get the measure from one vertice to an axis. An about two objects. You can disable axis to get only the distance between two points without using all axis.
