### ISSUE TITLE
Measurements get messy after modifier is applied.

### ISSUE THREAD

**Issue by trych** [Antonioya/blender#21]
The measurements get assigned to other, seemingly random vertices, when I apply a Boolean modifier on my model. I assume it probably messes up if there are vertices added to or deleted from the model and the vertex numbering changes.

Any way to fix this?

**Comment by Antonioya** [comment]
Sorry, No way to fix it.

The measure is using the vertex number, so when you apply the mod, all vertex numbering change, so the measures will be wrong. You have to redefine the measures again over the new mesh.
