### ISSUE TITLE
Blender 2.76 crashes with Archimesh

### ISSUE THREAD

**Issue by carroll6** [Antonioya/blender#26]
Got it installed..not sure if I got Archimesh installed right..everything is there.  Tried to use it with Grease Pencil.. blammo.. Blender crashes.. tried it twice now.  Hmm..I am not sure I downloaded it right I am using Windows 7.  I just used the grease pencil.. I didnt move anything to different layers or anything..just deleted the default cube.  hmm.  Nope, that wasnt it.   Do I have to download from RAW? I was in top down ORTHO mode.  UPDATE:  removed, installed again from Blender-Master.zip.  Used latest version..got the same result.. kablooey.

When I try to do ANYTHING..hit "room" hit "column".. bam..Blender just disappears.  No error message it just vanishes.  I have Win7, Athlon II quad core, ATI Firepro v4800.  

More investigation.  I have OpenCL on my system.  I tried earlier version of Archimesh.. 1.01.  Same result.. when I try to execute an operation Blender *poofs* on me.  Hope I dont have to buy new video card.  I was eager to use this tool for Unity.  Now I am looking for a low priced NVIDIA card that can run BLender and UNity.

**Comment by carroll6** [comment]
SOLVED.  Somehow, I had a NVidia control center installed.  Installed newest AMD Catalyst drivers and control center.  Now Blender works right, now Archimesh is working properly, and many thanks and praises for this wonderful software!!

**Comment by Antonioya** [comment]
Perfect!
