### ISSUE TITLE
Dimensions in mm

### ISSUE THREAD

**Issue by kroko** [Antonioya/blender#29]
Measure tool uses meters as a unit of measurement although world is set to scale 0.001.

This is an issue, for precision details (think of using Blender for 3D printing - it's not meant for MCAD, but people still use it for fast sketches or thingiverse assets).

Measure tool rounds to nearest 10^-2 m (centimeters). I.e. - position between two vertices is 16mm, however measure tool shows 0.02m (4mm is a lot).

Or maybe I'm missing something?

Thanks!

**Comment by Antonioya** [comment]
Have you set maximum decimal precision?
