### ISSUE TITLE
maybe not work blender..

### ISSUE THREAD

**Issue by manuelsongokuh** [Antonioya/blender#30]
hi
i love to use this measureit, but i find not work correct..see my screen record:
[vokoscreen-2016-03-30_19-17-04.mkv.zip](https://github.com/Antonioya/blender/files/196063/vokoscreen-2016-03-30_19-17-04.mkv.zip)

**Comment by manuelsongokuh** [comment]
version measureit 1.6.5 and blender 2.77.
linux

**Comment by Antonioya** [comment]
This is something related to the handler. Sometimes, when you reload a file or an add-on, the handler is not unloaded and remain active, and the button is not working as expected.

Usually, if you close Blender and enable again the add-on works...at least in Windows.

**Comment by mercedesmorita** [comment]
Para Blender 2.69 no me está funcionando. Habilité el addon corresponde, probé con distintas versiones, y se visualizan las herramientas y botones, pero cuando creo una medida no me aparece en el modelo 3D. Sólo me aparece en la barra del costado, confirmando que existe, pero no puedo visualizarla. Intenté con Show/Hide, y nada.
Ayer me andaba en Blender 2.75, en otra PC. Será un problema de compatibilidad con 2.69?

**Comment by Antonioya** [comment]
Creo que solo funciona a partir de la 2.74 o superior...con 2.69 es normal que no funcione. Yo lo desarrolle en 2.74 y no lo he probado en versiones anteriores.

**Comment by mercedesmorita** [comment]
Gracias por tu respuesta, Antonioya. Lo usare entonces con esa versión de Blender. Saludos.
