### ISSUE TITLE
version number

### ISSUE THREAD

**Issue by antonvdh** [Antonioya/blender#34]
Version number 1.1.1 is showing in blender when installed version 1.1.2 !

**Comment by Antonioya** [comment]
You are right. It was a problem creating the zip. You can download the right init.py here: https://github.com/Antonioya/blender/blob/master/archimesh/src/__init__.py

**Comment by antonvdh** [comment]
Thanks
Op 21 mei 2016 19:42 schreef "Antonioya" <notifications@github.com>:
