### ISSUE TITLE
wall name change

### ISSUE THREAD

**Issue by antonvdh** [Antonioya/blender#38]
Hello Antonioya can you tell me if it is possible to change the wall names.
I am modelling a Hotel from 1925 ( Hotel Luijk)
![archimesh-hotel](https://cloud.githubusercontent.com/assets/1901385/15580465/2219af64-2369-11e6-989e-0b6d98f7481c.png)

**Comment by Antonioya** [comment]
No, you can't...but you can use a trick. You can download my MeasureIt add-on and and any text at any place.

**Comment by antonvdh** [comment]
Wow thanks for the tip and awesome Measurelt add-on.
