### ISSUE TITLE
5-gons in door "Model 05" doors

### ISSUE THREAD

**Issue by muhuk** [Antonioya/blender#54]
The window faces consist of 5 vertices (not quads). This is true for both front and back.

![screenshot_20161203_133138](https://cloud.githubusercontent.com/assets/40178/20858743/f765b8da-b954-11e6-9d27-44df4312e369.png)

![screenshot_20161203_133339](https://cloud.githubusercontent.com/assets/40178/20858744/f769e4f0-b954-11e6-899b-347c30d23671.png)

As a manual workaround; selecting those vertices and merging them at the center seems to do the trick. (I had to do this because I needed to subdivide these faces for cycles)

-----

I have found the data arrays in the code. Is there a blend file and an import/export procedure that produce these arrays? (if there is I would like to try fixing this)

**Comment by Antonioya** [comment]
Hi,

Thanks for the bug report.

As you know, Archimesh is now part of Blender and it’s included with official build, so I have fixed the bug in Blender website, so it will be available in the next builds or official releases.

**Comment by muhuk** [comment]
Cool. Thanks for the info.
