### ISSUE TITLE
Feature Request for Doc Scenes Addon

### ISSUE THREAD

**Issue by aditiapratama** [Antonioya/blender#55]
Hi Antony, 

I just discovered this addon which is really useful for pre-production workflow. The feature that I would like to add is making storyboard based on marker,
- So, we can create marker on every shot that we want to make storyboard for
- or we can choose for every frame

Looking forward to hear from you.

**Comment by Antonioya** [comment]
I have a new add-on specially created for storyboarding and has these features and more.

Matias Mendiola is testing it but the add-on is not public yet.

**Comment by aditiapratama** [comment]
@Antonioya let me know if you need beta tester
