### ISSUE TITLE
Blender crash

### ISSUE THREAD

**Issue by allkhor** [Antonioya/blender#6]
**Hello**, thanks for your addon, it's very useful for me to save some time!
Little problem: one wall + floor = crash.
It's stupid create floor with only one wall, but blender should not crashed in any situation.
I tested **blender 2.69** and **blender 2.7 RC2** on **Ubuntu 13.10 x64** both crashed after select floor with wall. 

P.s Ceiling and one wall crash too.

**Comment by temkin** [comment]
Mac OS Yosemite, Blender 2.75 cannot install plugin, here is the screen: http://screencast.com/t/oXPYxQPI
