### ISSUE TITLE
Material and texture problem with the cabinet maker.

### ISSUE THREAD

**Issue by Shaba1** [Antonioya/blender#75]
I already posted this on blenderartist but thought I would drop it here too. This has to do with Archimesh Cabinet Maker.

"I am still using archimesh becasue it has some nice furnishing features that archipack does not have yet. Like cabinets, bookcases, lamps, curtains e.t.c. 

I have run into a problem though. I was making a cabinent which I was going to import into and archipack made room. I got ready to UV texture it and as you can see from the image it stays all white. I *THINK* this is because ARCHIMESH uses cycles materials automatically. I do not use cycle since I make most things for unity and unity does not have any knowledge of cycles but it will just import blender materials and uv texture. . 

PLEASE DO NOT give me advise on how I can export cycles to unity or how cycles it so much better then blender render or whatever. Just accept that I am and will be using blender materials and uv textures for the forseeable future.

In anycase is there a way of getting archimesh made items to use blender render materials and textures by default. I know there is a way of turning that off in the code for walls and rooms but I do not know how to do it for the rest of archimesh."

![image](https://user-images.githubusercontent.com/19808366/34856238-e19fba86-f6f8-11e7-8641-170251eb4bf2.png)

**Comment by Antonioya** [comment]
Hi,

Actually, Archimesh always use Cycles materials.

You can disable the materials for cycles at the end of the panel (last option), but what is not available is to create BI materials.

I don’t know if disable cycles is enough for you.

Regards,
Antonio Vazquez

**Comment by Shaba1** [comment]
Antionioya. That checkbox seems to be ghosted as you can see in the picture that I posted. I solved the problem anyway. I just manually created a Blender material and UV unwarpped the cabinet and added a image texture to it and turned on Textured solid in the 3D viewport. What I cannot determine is why when I go into textured mode by using the popup menu in the header the cabinet just goes all black even after all of the previous steps. But then it renders ok so I am happy. Just so it exports ok when I get ready to export. 

Thanks for the quick response..
