### ISSUE TITLE
Editable label --> parametric modelling

### ISSUE THREAD

**Issue by wstaelens** [Antonioya/blender#9]
If it would be possible to click the label with the measurement and adjust it, we would have basic Parametric CAD modelling!
see:
http://www.reddit.com/r/blender/comments/2h2o0a/how_i_imagine_parametric_cad_modeling_might_be/
and image: http://imgur.com/XXloJeB 

go for it! I buy you a beer!

**Comment by wstaelens** [comment]
reason why closed?

**Comment by Antonioya** [comment]
@wstaelens  Because this option is out of the scope of this project at this moment. Maybe in the future I will add this option, but now I haven't the time to do it.

**Comment by wstaelens** [comment]
ok great :+1:
